-- 예제 8.13 회원을 조회할 때 실행된 SQL

SELECT
    MEMBER.ID AS MEMBERID,
    MEMBER.AGE AS AGE,
    MEMBER.TEAM_ID AS TEAM_ID,
    MEMBER.USERNAME AS USERNAME,
    TEAM.ID AS TEAMID,
    TEAM.NAME AS NAME
FROM
    MEMBER MEMBER
LEFT OUTER JOIN
    TEAM TEAM ON MEMBER.TEAM_ID=TEAM1_.ID
WHERE
    MEMBER0_.ID='member1'
